### ISSUE TITLE
The ci config fields error

### ISSUE THREAD

**Issue by Mo3et** [ozline/tiktok#65]
Hello, I found your ci files have a typo in [.github/workflows/main.yaml](https://github.com/ozline/tiktok/blob/main/.github/workflows/main.yaml) and [.github/workflows/golangci-lint.yml](https://github.com/ozline/tiktok/blob/main/.github/workflows/golangci-lint.yml)

like line 8 is
```
  pull_request:
    branches:
      - main
```
no   `breanches`

**Comment by ozline** [comment]
Thank you! I did make a careless mistake while writing the scripts, but now it has been corrected!

Also, thank you for your interest in the project we are currently developing. This project underwent a major overhaul on August 10th. If you have any better suggestions or if you have discovered any other issues with this project, please feel free to provide your valuable feedback!
